name: PHP CI/CD

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: students
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl, pdo_mysql
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: |
        if [ -f "composer.json" ]; then
          composer validate --strict
        fi

    - name: Install dependencies
      run: |
        if [ -f "composer.json" ]; then
          composer install --prefer-dist --no-progress
        fi

    - name: PHP Lint
      run: |
        find . -type f -name '*.php' -print0 | xargs -0 -n1 php -l

    - name: Run test suite
      run: |
        if [ -f "phpunit.xml" ]; then
          vendor/bin/phpunit
        fi
